# yaml-language-server: $schema=https://raw.githubusercontent.com/mauriciobraz/vos/refs/heads/main/schemas/recipe.json

id: vesper-vanilla-desktop
name: Vesper's Vanilla Desktop

stages:
  - id: build
    base: ghcr.io/vanilla-os/desktop:main

    args:
      DEBIAN_FRONTEND: noninteractive

    labels:
      maintainer: Maurício Braz

    addincludes: true
    singlelayer: false

    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

    modules:
      - type: shell
        name: system
        commands:
          - lpkg --unlock
          - apt-get update

      # Customs
      # Customs

      - name: includes
        type: includes
        includes:
          - modules/01-apt.yml
          - modules/03-warp.yml
          - modules/04-howdy.yml
          - modules/05-iremitter.yml
          - modules/06-1password.yml

      # Cleanups
      # Cleanups

      - type: shell
        name: set-image-name
        commands:
          - IMAGE_NAME="$(cat /image-info/image-name)"
          - echo custom image name "$IMAGE_NAME"
          - IMAGE_NAME_ESCAPED="$(echo $IMAGE_NAME | sed 's/\//\\\//g')"
          - sed -i "s/changed_automatically_by_vib/$IMAGE_NAME_ESCAPED/g" /usr/share/abroot/abroot.json
          - rm -rf /image-info

      - type: shell
        name: system-cleanup
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock

      - type: fsguard
        name: fsguard

        GenerateKey: true
        CustomFsGuard: false

        FilelistPaths: ["/usr/bin"]
        FsGuardLocation: "/usr/sbin/FsGuard"

        modules:
          - type: shell
            name: setup
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - name: cleanup-temp
        type: shell
        commands:
          - rm -rf /tmp/*
          - rm -rf /sources
          - rm -rf /var/tmp/*

vibversion: 1.0.0
includespath: includes
