id: vesper
name: Vesper's Vanilla Desktop

stages:
  - id: build
    base: ghcr.io/vanilla-os/desktop:main
    singlelayer: false
    labels:
      maintainer: Maurício Braz
    args:
      DEBIAN_FRONTEND: noninteractive

    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

    modules:
      - name: init-setup
        type: shell
        commands:
          - lpkg --unlock
          - apt-get update

      # Put your custom actions below this comment
      # Put your custom actions below this comment

      - name: docker
        type: includes
        includes:
          - modules/50-install-docker.yml

      - name: howdy
        type: includes
        includes:
          - modules/50-install-howdy.yml

      - name: onepassword
        type: includes
        includes:
          - modules/50-install-onepassword.yml

      - name: packages
        type: apt
        sources:
          packages:
            - git
            - zsh
            - tar
            - pax
            - gzip
            - curl
            - fish
            - cmake
            - bzip2
            - unrar
            - unzip
            - podman
            - net-tools
            - ncompress
            - p7zip-full
            - libssl-dev
            - libffi-dev
            - pkg-config
            - python3-dev
            - python3-pip
            - build-essential

      - name: flatpak
        type: flatpak
        system:
          reponame: "flathub"
          repourl: "https://flathub.org/repo/flathub.flatpakrepo"
          install:
            - "com.obsproject.Studio"
            - "com.github.wwmm.easyeffects"
            - "com.obsproject.Studio.Plugin.DroidCam"

      - name: ssh-trust
        type: shell
        commands:
          - ssh-keyscan github.com gitlab.com >> /etc/ssh/ssh_known_hosts

      # Put your custom actions above this comment
      # Put your custom actions above this comment

      - name: set-image-name-abroot
        type: includes
        includes:
          - modules/80-set-image-abroot-config.yml

      - name: cleanup
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock

      - name: fsguard
        type: fsguard
        GenerateKey: true
        CustomFsGuard: false
        FilelistPaths: ["/usr/bin"]
        FsGuardLocation: "/usr/sbin/FsGuard"
        modules:
          - name: remove-prev-fsguard
            type: shell
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - name: cleanup2
        type: shell
        commands:
          - rm -rf /tmp/*
          - rm -rf /sources
          - rm -rf /var/tmp/*
