id: Vanilla
name: Vanilla

vibversion: 1.0.0
includespath: includes.container

stages:
  - id: build
    base: ghcr.io/vanilla-os/desktop:main
    args: { DEBIAN_FRONTEND: noninteractive }

    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

    modules:
      - type: shell
        name: system
        commands:
          - lpkg --unlock
          - apt-get update
          - apt-get upgrade -y

      - type: includes
        name: includes
        includes:
          - modules/00-apt.yaml
          - modules/10-docker.yaml
          - modules/11-tailscale.yaml
          - modules/12-1password.yaml
          - modules/13-zed-editor.yaml
          - modules/14-dx-imports.yaml
          - modules/15-ux-imports.yaml

      - name: add-image-name
        type: shell
        commands:
          - IMAGE_NAME="$(cat /image-info/image-name)"
          - echo custom image name "$IMAGE_NAME"
          - IMAGE_NAME_ESCAPED="$(echo $IMAGE_NAME | sed 's/\//\\\//g')"
          - sed -i "s/changed_automatically_by_vib/$IMAGE_NAME_ESCAPED/g" /usr/share/abroot/abroot.json
          - rm -rf /image-info

      - name: cleanup-a
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock

      - name: fsguard
        type: fsguard

        GenerateKey: true
        CustomFsGuard: false

        FilelistPaths: ["/usr/bin"]
        FsGuardLocation: "/usr/sbin/FsGuard"

        modules:
          - name: remove-prev-fsguard
            type: shell
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - name: cleanup-b
        type: shell
        commands:
          - rm -rf /tmp/*
          - rm -rf /var/tmp/*
          - rm -rf /sources

    addincludes: true
    singlelayer: false
