name: Vib Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: vanilla-os/vib-gh-action@v1.0.2
        with:
          recipe: "recipe.yaml"
          plugins: "Vanilla-OS/vib-fsguard:v1.6.1"

      - uses: actions/upload-artifact@v4
        with:
          name: Containerfile
          path: Containerfile

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --generate-notes Containerfile

      - name: Attest release files
        id: attest
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: "Containerfile"
